#!/usr/bin/env node
/**
 * Builds everything that has to be pasted somewhere during a deploy, into one
 * gitignored `deploy/` directory:
 *
 *   01-schema.sql    every migration, in order → Supabase SQL editor
 *   02-seed.sql      catalogue and demo data   → Supabase SQL editor
 *   vercel-env.txt   the environment variables → Vercel, Settings → Environment
 *
 * Why this exists: `supabase db push` needs the database password or a personal
 * access token, and a gym owner has neither to hand. The dashboard SQL editor
 * needs neither — open it, paste, run. Same idea for Vercel's env import box.
 *
 * The output contains real secrets and is generated, never committed.
 * Regenerate it after any schema or environment change.
 *
 *   npm run deploy:kit
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'deploy');
await mkdir(outDir, { recursive: true });

const rule = (char = '=') => '-- ' + char.repeat(75);
const banner = (title, sources) =>
  [rule(), `-- ${title}`, '--', '-- Generated by scripts/deploy-kit.mjs — do not edit, do not commit.',
   '-- Paste the whole file into the Supabase SQL editor and press Run.', '--',
   ...sources.map((s) => `--   ${s}`), rule(), '', ''].join('\n');

// ---------------------------------------------------------------- SQL bundles
const migrationsDir = join(root, 'supabase', 'migrations');
const files = (await readdir(migrationsDir)).filter((f) => f.endsWith('.sql')).sort();

let schema = banner('Iron Core Gym — schema, functions, RLS and storage', files);
for (const file of files) {
  schema += `\n\n${rule('-')}\n-- ${file}\n${rule('-')}\n\n`;
  schema += (await readFile(join(migrationsDir, file), 'utf8')).trimEnd() + '\n';
}
await writeFile(join(outDir, '01-schema.sql'), schema + '\n');

const seed = await readFile(join(root, 'supabase', 'seed.sql'), 'utf8');
await writeFile(
  join(outDir, '02-seed.sql'),
  banner('Iron Core Gym — catalogue and demo data (safe to re-run)', ['supabase/seed.sql']) + seed.trimEnd() + '\n',
);

// ------------------------------------------------------------- Vercel env file
// Only variables that belong in a deployment. Anything absent from .env.local is
// skipped rather than emitted blank, so Vercel does not end up with empty keys
// that shadow a provider's own default.
const WANTED = [
  'NEXT_PUBLIC_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_ROLE_KEY',
  'AUTH_SECRET', 'CRON_SECRET', 'NEXT_PUBLIC_SITE_URL',
  'NEXT_PUBLIC_DEMO_MODE', 'DEMO_MODE', 'MEMBER_EMAIL_DOMAIN',
  'RAZORPAY_KEY_ID', 'RAZORPAY_KEY_SECRET', 'NEXT_PUBLIC_RAZORPAY_KEY_ID', 'RAZORPAY_WEBHOOK_SECRET',
  'SMS_PROVIDER', 'MSG91_AUTH_KEY', 'MSG91_SENDER_ID', 'MSG91_TEMPLATE_ID', 'MSG91_OTP_TEMPLATE_ID',
  'TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN', 'TWILIO_FROM',
  'WHATSAPP_PROVIDER', 'WHATSAPP_PHONE_NUMBER_ID', 'WHATSAPP_ACCESS_TOKEN', 'TWILIO_WHATSAPP_FROM',
  'EMAIL_PROVIDER', 'RESEND_API_KEY', 'EMAIL_FROM',
];

const local = Object.fromEntries(
  (await readFile(join(root, '.env.local'), 'utf8').catch(() => ''))
    .split(/\r?\n/)
    .filter((l) => l.trim() && !l.trim().startsWith('#') && l.includes('='))
    .map((l) => [l.slice(0, l.indexOf('=')).trim(), l.slice(l.indexOf('=') + 1).trim()]),
);

const lines = [
  '# Iron Core Gym — paste into Vercel: Settings → Environment Variables → import .env',
  '#',
  '# Generated by scripts/deploy-kit.mjs. Contains real secrets: never commit this.',
  '#',
  '# After adding the custom domain, change NEXT_PUBLIC_SITE_URL to match and',
  '# redeploy — that value is what appears in links inside SMS and WhatsApp.',
  '#',
  '# DEMO_MODE shows login codes on screen. It is on because no SMS gateway is',
  '# configured yet, and without it nobody can sign in at all. Turn both DEMO_MODE',
  '# variables off the moment real members are added.',
  '',
];
const PLACEHOLDER = 'https://REPLACE-WITH-YOUR-VERCEL-URL';
for (const key of WANTED) {
  let value = local[key];
  if (!value) continue;
  // A localhost site URL in production would put unreachable links inside every
  // reminder SMS. Emit something obviously wrong rather than something quietly
  // broken, so it gets corrected before anyone is messaged.
  if (key === 'NEXT_PUBLIC_SITE_URL' && /localhost|127\.0\.0\.1/.test(value)) {
    lines.push(`# ↓ was ${value} locally — set this to the real domain before going live`);
    value = PLACEHOLDER;
  }
  lines.push(`${key}=${value}`);
}
await writeFile(join(outDir, 'vercel-env.txt'), lines.join('\n') + '\n');

const missing = WANTED.filter((k) => !local[k]);
console.log(`deploy/01-schema.sql    ${Math.round(schema.length / 1024)} KB  (${files.length} migrations)`);
console.log(`deploy/02-seed.sql      ${Math.round(seed.length / 1024)} KB`);
console.log(`deploy/vercel-env.txt   ${lines.filter((l) => l.includes('=')).length} variables`);
if (missing.length) console.log(`\nnot set locally, so not exported: ${missing.join(', ')}`);
console.log('\nSupabase SQL editor: run 01 then 02.  Vercel: import vercel-env.txt.');
